### ISSUE TITLE
Relocate Build Template Wizard

### ISSUE THREAD

**Issue by claytondaley** [Skibisky/RuneManager#48]
I don't find this screen useful at all.  It prompts you to populate "goals" when I want to be using minimums/maximums.  The templates are certainly interesting as examples, but I've never used one.  I suggest replacing this step with a button or dropdown on the builds page that lets you load an optimization template.  The dropdown might default to "custom" but let you pick one of these other options.

**Comment by Skibisky** [comment]
In the options menu, you can disable 'Show Build Wizard'.
There is a tick-box down the bottom which will also disable it, but you need to select '<None>' as the build.
Admittedly, there is a bug where that checkbox is disabled until you select another template, then reselect '<None>'.

The Build Wizard is supposed to be a simplified entry point into creating builds.
So that if someone isn't comfortable with specifying everything needed for a correct build, one of the templates not only will be valid, but show a possible preview of how the scoring works.

Goals are a softer minimum, as using minimum naively will result in no builds, where using Goal will "always" result in a build.

Additionally, in the templates.json file you can specify a URL/file to load _more_ templates from (which is where the EU2K comes from).
This would allow someone to create a 'useful' set of templates for specific monsters and share them.

Personally, I use them as a starting point when bringing in a new monster, just as a rough starting point.

**Comment by claytondaley** [comment]
I understand your point about goals, but most suggested builds (GB10, R5, etc.) have pretty hard EHP minimums.  I also don't understand what it would do if I have SPD and EHP minimums and both cannot be met at the same time.  At least a minimum will hard lock so I can either reprioritize or lower my targets.

And if I'm not confident how they'd behave (as a relatively experienced user), I have to believe the behavior would simply frustrate a new user.

**Comment by claytondaley** [comment]
The templates make more sense to me as guides.  That's why I was still trying to preserve them.  Maybe a checkbox that says "down show this screen in the future (can re-enable in settings)".

**Comment by claytondaley** [comment]
It'd be nice to add a checkbox to the bottom so you don't have to go to setting to hide, but there are more important/valuable improvements.
