### ISSUE TITLE
Consider Making "run to" Include the Selection Monster

### ISSUE THREAD

**Issue by claytondaley** [Skibisky/RuneManager#60]
If I select a mon and choose "run to", it appears to stop on the previous mon.  That's not my intuition.  On the one hand, "just run that next mon" seems logical.  On the other, it makes sense to stop after a long-running monster so "just running it" could mean hours of waiting.

**Comment by Skibisky** [comment]
Hmm. The inspiration behind 'run to' is that it will lock in all the runes of the monsters above them, so that you can start testing and tweaking the target monster without the runes that will be used by other monsters.

Removing 1 build is faster than waiting for it to finish, so this sounds like a fair enough change.
